project:
  type: website

website:
  title: Hollywood Age Gap
  navbar:
    right:
      - icon: github
        href: https://github.com/math241s24/project01-team-hollywood-age
    left:
      - text: Project
        href: index.qmd
      - text: "Hollywood Age Gap Final Project Proposal"
        href: proposal.qmd
      - text: "Project Presentation"
        href: presentation.qmd
      - text: "About Hollywood Age Gap"
        href: about.qmd

format:
  html:
    theme: default
    toc: true

execute:
  freeze: auto
