---
title: "Hollywood Age Gap Final Project Proposal"
format: html
editor: visual
---

# Proposal

Hollywood Age Gap 

Dataset description: The data was compiled by Lynn Fisher, a web designer. The dataset lists movies featuring romantic couples as observations, and their respective release years, actor names, birthdates, age gaps, and genders.

```{r}
library(readr)
library(tidytuesdayR)
age_gaps <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-02-14/age_gaps.csv", show_col_types = FALSE)

```

Dimensions: \[1\] 1177 12

Why we chose it: We chose this dataset because we were intrigued by the cultural representation of romantic relationships in cinema and how they create social norms and dynamics particularly in regards to gendered expectations.

Questions: Are men typically the older person in the age gap, and has this changed over time?

Are certain directors more likely to have larger age gaps in their films than others?\

Variables:

release_year : This variable is a numeric variable that tells the release year of each movie in the data set, this is the variable we will use to track change over time

director : This is a character variable that tells the name of the director for each movie

age-difference : This is a numeric variable that expresses the difference in age between the tow actors

actor_1_age and actor_2_age: these two character variables reflect the ages of both actors, we will use these variables in combination with the gender variables to determine whether men are typically the older one in the age gap

actor_1_gender and actor_2_age : these two numeric variables reflect the genders of both actors, we will use these variables in combination with the age variables to determine whether men are typically the older one in the age gap

Our plan :

Create a variable for average mean age gap between actors for each director; we can facet or color by director to achieve this. Since there are \>500 directors, we will select the ten with the most movies in the dataset (Woody Allen, John Glen, Martin Scorsese, Mike Newell, Steven Spielberg, Christopher Nolan, David Fincher, Dennis Dugan, Guy Hamilton, and Mike Nichols). These directors are household names and will likely be of interest to our audience. To indicate that a director is an outlier, we can make a box plot and find summary statistics, and then find the directors that are outliers to our expectations.

Create a visualization contrasting age gaps in different movies by gender over time

Create a visualization showing average age gap for each director with several movies on the list

\
\
